runtime: python37 # or another supported version
instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: 'root' 
  MYSQL_PASSWORD: 'cs411' 
  MYSQL_DB: 'db'
  MYSQL_HOST: '34.70.128.74'


# handlers:
# - url: /script
# static_dir: static/script
# - url: /styles
# static_dir: static/styles